/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marialaura' at '03/11/16 16.24' with Gradle 2.14.1
 *
 * @author marialaura, @date 03/11/16 16.24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
